language: python
python:
  - "2.7"
  - "3.6"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y astyle
# command to install dependencies
install: pip install tox-travis
# command to run tests
script:
  tox
